version: "3.8"

services:

  ltl_api:
    build:
      context: ../API
      dockerfile: api.dockerfile
    container_name: ltl_api
    env_file:
      - .env
    ports:
      - "8090:8000"
    volumes:
      - ../API:/LittleAPI
    networks:
      - ltl-fullstack-net
    command: python3 main.py


  mongo:
    image: mongo
    container_name: '${MONGO_HOST}'
    ports:
      - "27001:27001"
    volumes:
      - ./Data/Mongo/:/data/db
    env_file: .env
    networks:
      - ltl-fullstack-net
    command: mongod --quiet --logpath /dev/null --port 27001

  web:
    image: node:19-alpine
    container_name: LittleReact
    ports:
      - "80:80"
    volumes:
      - ../web:/web
      - exclude:/web/node_modules
    working_dir: /web
    env_file: .env
    networks:
      - ltl-fullstack-net
    command: sh -c "echo "VITE_API_ROOT=${DEV_API_ENDPOINT}" > .env.development && npm i && npm run dev -- --port 80 --host 0.0.0.0;"


networks:
  ltl-fullstack-net:
    driver: bridge

volumes:
    exclude: